version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: ".github/actions/**/action.yml"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
